### PR TITLE
OOP Assignment - Deck of card the can be shuffled using 3 methods

### PR DESCRIPTION
**Pull request by Jacob-Cheadle**
26371737 - Jacob Cheadle
This is a program based off the brief given by the client in which a deck of cards is created, can be shuffled in 3 different ways and allows cards to be drawn from the deck.

Attached is an image of the program function

image

### CODE REVIEW

**Comment by BSpoones** [comment]
Name: Ben Soones (26511258)

Code Suggestion

Your switch statements have been very effectively implemented in your conversion between card suits and values to names. However, I would suggest for you to create a list or an enum to convert card values to names. Also I noticed that you used a repeat of a switch case twice in your testing class. If you declare a function and put your switch case there it can reduce any repetitive code.

Error handling

Your error handling has been done very efficiently, with a clear message for your handling of user inputs. I would recommend that you catch the exact exception and writing the message to the console. This would allow for handling of text inputs as well as empty inputs.

Documentation

Your comments and documentation are done very cleanly. It is clear that you have put a lot of effort into ensuring that a viewer of any skill level can understand how your code works. To ensure that users can easily comprehend how to use each function and class, you should consider adding a readme to your repository.

**Comment by Jacob-Cheadle** [comment]
Added a ReadMe file to make the users experience with the program better, is there anything else you would recommend I add to the text file?
[ReadMe.md.txt](https://github.com/Jacob-Cheadle/CMP1903M-OOP/files/10926268/ReadMe.md.txt)

**Comment by FawksX** [comment]
Name: Oliver Whitehead (26435141)

**Code Suggestion**

While your cards are implemented correctly I think we could reduce some extra lines of code by adding parameters to the constructor of the card (the Suit and Value). This will remove lines 19 and 20 in the `Pack` class.
I also noticed that within the `Testing` class, you do not deal after each shuffle to test it is shuffled. I would recommend abstracting your Test method so that each test can run fully instead of just the last one in the group.

**Error Handling**
Your Error Handling for the program is generally very good, however specifying within the `set` method of your `Card` to ensure that only numbers between 1 and 13 are set would be good for validation of the users input. If it is not within this range an exception should be thrown.

**Documentation**
Throughout your program your comments are clear and concise and easy to read. I would suggest adding some header comments to public methods which may be used by other developers to give an overview of how the method works.

**Comment by AlexBarberLincs** [comment]
Alex Barber 26531201

Your code effectively handles errors and leaves a clear record for how you handle user inputs. I recommend you to log the message to the console. 

You included a readme after a suggestion was made, this ensures your console app is properly documented, complimenting your well made app.

I’m not quite sure what I would recommend to be improved, as the app is solid and punches far above what I can achieve. Well done.

**Comment by oJo56** [comment]
Oliver Jones - 26404840

Your code is clearly very well thought out and executed. Although it may not be perfectly optimised, it is still suitably efficient to run quickly and without any errors. Your error handling is also done very effectively, allowing the programmer or the user to see any errors that may come up, whether it be during runtime or compilation. Your comments are clear and concise allowing any person who wishes to read long through your code to do so with much ease. The only things I could possibly recommend is some greater optimisation and reduction of lines in some of the classes.

**Comment by Jacob-Cheadle** [comment]
Added a function to remove the duplicate switch case code to improve conciseness.
`public string valueConverter(string valueType, string value)
        {
            if (valueType == "Suit")
            {
                string strSuit = value;
                switch (strSuit) //reassigns the number values to their corresponding suits
                {
                    case "1":
                        strSuit = "Spades";
                        break;
                    case "2":
                        strSuit = "Clubs";
                        break;
                    case "3":
                        strSuit = "Diamonds";
                        break;
                    case "4":
                        strSuit = "Hearts";
                        break;
                    default:
                        strSuit = strSuit;
                        break;
                }
                return strSuit;
            }
            else
            {
                string strValue = value;
                switch (strValue) //reassigns the number values to their corresponding card types
                {
                    case "1":
                        strValue = "Ace";
                        break;
                    case "2":
                        strValue = "Two";
                        break;
                    case "3":
                        strValue = "Three";
                        break;
                    case "4":
                        strValue = "Four";
                        break;
                    case "5":
                        strValue = "Five";
                        break;
                    case "6":
                        strValue = "Six";
                        break;
                    case "7":
                        strValue = "Seven";
                        break;
                    case "8":
                        strValue = "Eight";
                        break;
                    case "9":
                        strValue = "Nine";
                        break;
                    case "10":
                        strValue = "Ten";
                        break;
                    case "11":
                        strValue = "Jack";
                        break;
                    case "12":
                        strValue = "Queen";
                        break;
                    case "13":
                        strValue = "King";
                        break;
                    default:
                        strValue = strValue;
                        break;
                }
                return strValue;
            }
        }`

**Comment by Jacob-Cheadle** [comment]
Added more detailed error handling so that the user is aware of what the issue with their input was.

**Comment by Jacob-Cheadle** [comment]
>Oliver Jones - 26404840

> Your code is clearly very well thought out and executed. Although it may not be perfectly optimised, it is still suitably efficient to run quickly and without any errors. Your error handling is also done very effectively, allowing the programmer or the user to see any errors that may come up, whether it be during runtime or compilation. Your comments are clear and concise allowing any person who wishes to read long through your code to do so with much ease. The only things I could possibly recommend is some greater optimisation and reduction of lines in some of the classes.

Removed unnecessary blank lines to reduce line count however the rest of the code is pretty optimised I would say, I may see some more things to optimise later however I can't see anything that needs urgently changing, if you have any suggestions please let me know.

**Comment by Jacob-Cheadle** [comment]
> Name: Ben Soones (26511258)
> 
> Code Suggestion
> 
> Your switch statements have been very effectively implemented in your conversion between card suits and values to names. However, I would suggest for you to create a list or an enum to convert card values to names. Also I noticed that you used a repeat of a switch case twice in your testing class. If you declare a function and put your switch case there it can reduce any repetitive code.
> 
> Error handling
> 
> Your error handling has been done very efficiently, with a clear message for your handling of user inputs. I would recommend that you catch the exact exception and writing the message to the console. This would allow for handling of text inputs as well as empty inputs.
> 
> Documentation
> 
> Your comments and documentation are done very cleanly. It is clear that you have put a lot of effort into ensuring that a viewer of any skill level can understand how your code works. To ensure that users can easily comprehend how to use each function and class, you should consider adding a readme to your repository.

I have completed all of these suggestions and pushed them to development if you have any further review suggestions or improvements.
- I have created a function to remove the duplicate switch statements.
- I have decided not to use a list or enum for this as although there are more lines used, I personally prefer using switch case, I may change this in future.
- I have implemented the error catching that allows for handling of all inputs.
image
- I have added a ReadMe.txt file to my Repository that explains the usage of the program.
[ReadMe.md.txt](https://github.com/Jacob-Cheadle/CMP1903M-OOP/files/10927547/ReadMe.md.txt)

**Comment by Jacob-Cheadle** [comment]
> Alex Barber 26531201
> 
> Your code effectively handles errors and leaves a clear record for how you handle user inputs. I recommend you to log the message to the console.
> 
> You included a readme after a suggestion was made, this ensures your console app is properly documented, complimenting your well made app.
> 
> I’m not quite sure what I would recommend to be improved, as the app is solid and punches far above what I can achieve. Well done.

The logging is already done in my Testing.cs class I'm pretty sure, is this what you mean?

**Comment by Jacob-Cheadle** [comment]
> Name: Oliver Whitehead (26435141)
> 
> **Code Suggestion**
> 
> While your cards are implemented correctly I think we could reduce some extra lines of code by adding parameters to the constructor of the card (the Suit and Value). This will remove lines 19 and 20 in the `Pack` class. I also noticed that within the `Testing` class, you do not deal after each shuffle to test it is shuffled. I would recommend abstracting your Test method so that each test can run fully instead of just the last one in the group.
> 
> **Error Handling** Your Error Handling for the program is generally very good, however specifying within the `set` method of your `Card` to ensure that only numbers between 1 and 13 are set would be good for validation of the users input. If it is not within this range an exception should be thrown.
> 
> **Documentation** Throughout your program your comments are clear and concise and easy to read. I would suggest adding some header comments to public methods which may be used by other developers to give an overview of how the method works.

- Added parameters to the constructor to allow cleaner card creation.
- Dealing is now done after each shuffle and a reset function has been made to reset the pack after each shuffle and dealing.
image
- Error handling has been completed, no error handling was required in the constructor as only certain values can be passed in and these cannot be changed so error handling here would only add extra useless logic and slow down the program.
- Header comments have been added to the functions, classes and general processes to further explain their usage.

Everything has been implemented from this review, of there are any corrections you would recommend please feel free to add them.

**Review by Jacob-Cheadle — COMMENTED** [review]
Removed Unnecessary Lines
Completed The Program To An Adequate Standard
Added A ReadMe File

**Pull request merged**
